apiVersion: v1
kind: Namespace
metadata:
  name: backend

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
      - name: flask-app
        image: ahmedemad2025/flask-app
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: backend-server
  ports:
  - port: 5000
    targetPort: 5000

