apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask
  namespace: backend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: flask-app
        image: ahmedemad2025/flask-app:v3
        ports:
        - containerPort: 5000